In [1]:
import numpy as np
import pandas as pd


In [ ]:
#NUMPY AND PANDAS

In [ ]:
#1,create a numpy array containing the numbers from 1 to10,and then reshape it to a 2*5 matrix.

In [5]:
array= np.arange(1,11).reshape(2,5)
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#2,create a numpy array containing the numbers from 1 to 20,and then extrat the element between the 5th and 15th index.

In [10]:
array=np.arange(1,21)
extracted_element=array[4:15]
print(extracted_element)

[ 5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
#3,how to complete the mean ,median,and standard deviation of a numpy array?use the array you creatted above.

In [20]:
array=np.arange(1,11).reshape(2,5)
print(np.mean(array))
print(np.median(array))
print(np.std(array))

5.5
5.5
2.8722813232690143


In [ ]:
#4.write numpy program that creates a 2A array x of shape(3,4) and a 1D array of shape(4,).subtract y from each row of xusing broadcasting

In [21]:
x=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
y=np.array([1,2,3,4])
print(x-y)

[[  9  18  27  36]
 [ 49  58  67  76]
 [ 89  98 107 116]]


In [ ]:
#5,create a dataframe with the following coiumns,age,and ggender.the dataframe should have 10rows of data.

In [26]:
df=pd.DataFrame({
    'name':['alice','bob','charlie','eva','david','frank','grace','hannah','ian','jack'],
    'age':[25,32,28,45,22,38,29,31,40,26],
    'gender':['female','male','male','male','male','female','male','female','female','male']
})
print(df)


      name  age  gender
0    alice   25  female
1      bob   32    male
2  charlie   28    male
3      eva   45    male
4    david   22    male
5    frank   38  female
6    grace   29    male
7   hannah   31  female
8      ian   40  female
9     jack   26    male


In [ ]:
#5.1,add a new coiumn to the dataframe created in question 1[note:referring to the datafram],called occupation.the values for this column should be programmer,manager,and analyst,corresponding to the rows in the dataframe.

In [27]:
#add occupation
df['occupation']=['programmer','manager','analyst','programmer','manager','analyst','analyst','programmer','manager','manager']
print(df)

      name  age  gender  occupation
0    alice   25  female  programmer
1      bob   32    male     manager
2  charlie   28    male     analyst
3      eva   45    male  programmer
4    david   22    male     manager
5    frank   38  female     analyst
6    grace   29    male     analyst
7   hannah   31  female  programmer
8      ian   40  female     manager
9     jack   26    male     manager


In [30]:
#5.2,select the rows of the dataframe where the age is greater than or equal to 30
#age>=30
print(df[df['age']>=30])

     name  age  gender  occupation
1     bob   32    male     manager
3     eva   45    male  programmer
5   frank   38  female     analyst
7  hannah   31  female  programmer
8     ian   40  female     manager


In [31]:
#5.3,convert this dataframe to a csv file and read that csv file,and finally display the contents
#5.3,save and read csv
df.to_csv('data.csv',index=False)
print(pd.read_csv('data.csv'))

      name  age  gender  occupation
0    alice   25  female  programmer
1      bob   32    male     manager
2  charlie   28    male     analyst
3      eva   45    male  programmer
4    david   22    male     manager
5    frank   38  female     analyst
6    grace   29    male     analyst
7   hannah   31  female  programmer
8      ian   40  female     manager
9     jack   26    male     manager
